version: '3.9'

services:

  composer:
    image: composer:2.3.5
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: composer install

  php:
    depends_on:
      composer:
        condition: service_completed_successfully
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    volumes:
      - ./:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      
  nginx:
    depends_on:
      php:
        condition: service_healthy
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
