version: '3.9'

services:
      
  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - 3306:$MYSQL_PORT
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: mysql -u $$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 5m

  composer:
    image: composer:2.3.5
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: composer install

  php:
    depends_on:
      mysql:
        condition: service_healthy
      composer:
        condition: service_completed_successfully
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    volumes:
      - ./:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      
  nginx:
    depends_on:
      php:
        condition: service_healthy
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

volumes:
  db-data:
